# Generated by Django 3.1.1 on 2020-10-11 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('description', models.CharField(max_length=128, verbose_name='内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='コメント数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_me', to=settings.AUTH_USER_MODEL, verbose_name='自分・ユーザー')),
            ],
            options={
                'verbose_name_plural': 'sns',
                'db_table': 'sns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LikeOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_up', models.BooleanField(default=False)),
                ('sns', models.ManyToManyField(to='sns.Sns', verbose_name='メンション')),
            ],
            options={
                'db_table': 'favorite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_me', to=settings.AUTH_USER_MODEL, verbose_name='自分・ユーザー')),
                ('my_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='フレンズ')),
            ],
            options={
                'verbose_name': 'フレンド',
                'db_table': 'friend',
                'managed': True,
            },
        ),
    ]
