# Generated by Django 3.1.2 on 2020-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='description',
            field=models.TextField(max_length=128, verbose_name='内容'),
        ),
    ]
