# Generated by Django 3.1.2 on 2020-10-14 22:28

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0002_auto_20201014_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/',
                                    validators=[django.core.validators.FileExtensionValidator(['png'])],
                                    verbose_name='投稿画像'),
        ),
        migrations.CreateModel(
            name='SnsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                          to=settings.AUTH_USER_MODEL)),
                ('sns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.sns')),
            ],
            options={
                'db_table': 'sns_comment',
                'managed': True,
            },
        ),
    ]
