# Generated by Django 3.1.2 on 2020-10-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20201015_0728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnsComment',
        ),
    ]
