# Generated by Django 3.1.2 on 2020-10-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns_comment', '0002_remove_snscomment_sns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0004_delete_snscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sns_comment.snscomment', verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='me',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sns_me', to=settings.AUTH_USER_MODEL, verbose_name='自分・ユーザー'),
        ),
    ]
