# Generated by Django 3.1.2 on 2020-10-19 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0005_auto_20201019_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_me', to=settings.AUTH_USER_MODEL, verbose_name='自分・ユーザー'),
        ),
    ]
