# Generated by Django 3.1.2 on 2020-10-16 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sns', '0004_delete_snscomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=128, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('me', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='コメント者')),
                ('sns', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sns.sns', verbose_name='mention_id')),
            ],
            options={
                'db_table': 'sns_comment',
                'managed': True,
            },
        ),
    ]
