# Generated by Django 3.0.3 on 2020-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=32)),
                ('due_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'todo',
                'managed': True,
            },
        ),
    ]
